"""Phase 3 canvas work artifact — the student's submitted work, stored once
per attempt as a single PDF plus its ordered per-page OCR text.

The binary stays in the storage service; this repo only exchanges references
and metadata over the Student Model HTTP boundary.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class WorkArtifactPersistRequest(BaseModel):
    student_id: str
    topic_id: str
    question_id: str
    question_usage_id: str
    page_count: int = Field(ge=1)
    combined_pdf_base64: str
    # Ordered page OCR, page 1 first, alongside the combined text; the spec
    # requires both so Phase 4 can read the work without rerunning OCR.
    per_page_ocr_text: list[str]
    combined_ocr_text: str


class WorkArtifactPersistResponse(BaseModel):
    # Generated by the storage service, never invented here.
    artifact_id: str
    pdf_url: str
    page_count: int


class Phase4ReviewPersistRequest(BaseModel):
    """The finished Phase 4 review, for the reusable topic learning summary."""

    student_id: str
    topic_id: str
    # Replay detail belongs in phase_4_summary_json; the narrative fields and
    # key takeaways are also shown to the student.
    tutor_replays: list[dict[str, object]]
    student_insights: dict[str, object]
