"""CG-006: map a parsed topic document onto NormalizedTopicBrief.

CG-005 reads the document's structure without interpreting it. This module does
the interpreting: it decides which heading feeds which field, flattens Word's
mix of paragraphs and bullets into the strings and lists the model expects, and
validates the result through Pydantic.

Field sources
-------------

    topic_id                    "Topic ID: ALG-ORI-01" under Section A
    topic_code                  derived, "T01" ... "T06"
    topic_title                 document title, minus the "Topic N - " prefix
    ks_stage                    "Audience: KS3 students, ages 11-14"
    sequence_no                 the N in "Topic N"
    learning_goal               Section A > Learning Goal
    core_message                Section A > Core Message
    included_scope              Section A > Included
    excluded_scope              Section A > Excluded
    misconceptions_to_prevent   Section A > Misconceptions to Prevent
    golden_rules                Section B > Part 2 - Golden Rules
    storyboard_notes            Section B > Part 3 - Storyboard and Script
    source_file_name            the filename

A note on fidelity
------------------

The brief is a faithful record of what the document says, not a polished
version of it. The reference workbook's Topics sheet is *not* a verbatim copy
of these documents -- it is editorially rewritten. For Topic 2 the reference
drops the "Students should " preamble; for Topic 3 it condenses a bulleted list
into one sentence; for Topic 1 it is different prose altogether. That rewriting
is a downstream, LLM-driven step (see the NormalizedTopicBrief docstring: "This
is NOT generated by the LLM -- it's parsed from the document"). Trying to
reproduce it deterministically here would be guessing, so this module does not.

Two source oddities worth knowing about
---------------------------------------

* Topic 1's document is the outlier: fewer Section B subsections than the other
  five, and no "Expected Student Outcome". Nothing here depends on those.
* The reference workbook lists Topic 1 as ALG-KS3-01 while its document, and
  every other document, uses the ALG-ORI-NN form. The document wins, on the
  grounds that all six agree with each other and the reference only covers
  three topics. Flagged rather than silently reconciled; CG-008 reports it.
"""

from __future__ import annotations

import re
from typing import Optional

from docx_parser import (
    ParsedTopicDocument,
    Section,
    parse_all_topic_documents,
)
from models import KSStage, NormalizedTopicBrief

GOLDEN_RULES_HEADING = "Golden Rules"
STORYBOARD_HEADING = "Storyboard and Script"

KS_STAGE_RE = re.compile(r"\bKS\s*([34])\b", re.IGNORECASE)
METADATA_RE = re.compile(r"^\s*([A-Za-z][A-Za-z /]*?)\s*:\s*(.+)$")

# Scope headings whose content must be a non-empty list.
SCOPE_FIELDS = {
    "included_scope": "Included",
    "excluded_scope": "Excluded",
    "misconceptions_to_prevent": "Misconceptions to Prevent",
}

# Prose headings whose content must be a non-empty string.
PROSE_FIELDS = {
    "learning_goal": "Learning Goal",
    "core_message": "Core Message",
}


class BriefMappingError(Exception):
    """The document parsed, but does not carry what the brief requires."""


# ──────────────────────────────────────────────────────────────────────
# Flattening helpers
# ──────────────────────────────────────────────────────────────────────

def items_of(section: Optional[Section]) -> list[str]:
    """Every line under a heading, as a list.

    Deliberately takes all paragraphs rather than only the ones Word marks as
    list items. Under the scope headings the two are the same -- all six
    documents mark every line -- but Golden Rules is not so tidy: Topic 6 has
    two rules written as plain paragraphs. Filtering on the list marker there
    would silently drop them.
    """
    if section is None:
        return []
    return [p.text for p in section.paragraphs]


def prose_of(section: Optional[Section]) -> str:
    """A heading's content as one readable string.

    Some Learning Goal sections are a single paragraph; others are a lead-in
    line followed by bullets. Bullets are joined with semicolons so the lead-in
    still reads as a sentence rather than running into the first bullet.
    """
    if section is None:
        return ""

    lead = [p.text for p in section.paragraphs if not p.is_list_item]
    bullets = [p.text for p in section.paragraphs if p.is_list_item]

    if not bullets:
        return " ".join(lead).strip()

    joined = "; ".join(b.rstrip(".;") for b in bullets)
    if not lead:
        return joined
    head = " ".join(lead).strip()
    separator = " " if head.endswith(":") else ": "
    return f"{head}{separator}{joined}"


def metadata_of(section: Optional[Section]) -> dict[str, str]:
    """"Key: value" lines sitting directly under a section heading.

    Section A opens with Topic ID, Audience, Orientation video and Duration
    before its first subsection. Keys are lowercased for lookup.
    """
    if section is None:
        return {}
    found: dict[str, str] = {}
    for para in section.paragraphs:
        match = METADATA_RE.match(para.text)
        if match:
            found.setdefault(match.group(1).strip().lower(), match.group(2).strip())
    return found


def storyboard_notes_of(section_b: Optional[Section]) -> str:
    """Part 3 flattened into readable notes.

    Each scene is an H3 with its own paragraphs and a two-column table of
    visual action and narration. The table rows are included because the
    narration is the only place the approved wording appears.
    """
    if section_b is None:
        return ""
    part3 = _find_subsection(section_b, STORYBOARD_HEADING)
    if part3 is None:
        return ""

    lines: list[str] = [p.text for p in part3.paragraphs]

    for scene in part3.subsections.values():
        lines.append(scene.heading)
        lines.extend(p.text for p in scene.paragraphs)
        for table in scene.tables:
            for row in table:
                cells = [c.replace("\n", " ").strip() for c in row if c.strip()]
                if cells:
                    lines.append(" | ".join(cells))

    return "\n".join(line for line in lines if line).strip()


def _find_subsection(section: Section, needle: str) -> Optional[Section]:
    """Find a subsection whose heading contains `needle`.

    Section B headings are prefixed and use an em dash ("Part 2 - Golden
    Rules"), and Topic 1 numbers its parts differently from the rest, so an
    exact-name lookup is too brittle. Matching on the distinctive part of the
    heading is not.
    """
    wanted = needle.strip().lower()
    for heading, sub in section.subsections.items():
        if wanted in heading.strip().lower():
            return sub
    return None


def _ks_stage(doc: ParsedTopicDocument) -> KSStage:
    """Read the key stage from the Audience line, defaulting to KS3.

    Every current document says "Audience: KS3 students, ages 11-14". Reading
    it rather than hardcoding means a KS4 document would be caught by the enum
    instead of being silently mislabelled.
    """
    concept = doc.concept_sheet
    if concept is not None:
        audience = metadata_of(concept).get("audience", "")
        match = KS_STAGE_RE.search(audience)
        if match:
            return KSStage(f"KS{match.group(1)}")
    return KSStage.KS3


# ──────────────────────────────────────────────────────────────────────
# Mapping
# ──────────────────────────────────────────────────────────────────────

def to_normalized_brief(doc: ParsedTopicDocument) -> NormalizedTopicBrief:
    """Turn one parsed document into a validated NormalizedTopicBrief.

    Raises BriefMappingError, naming the document and the missing piece, when
    something the brief requires is absent. Section B is optional: a document
    with no designer handoff still produces a brief, with empty golden rules
    and storyboard notes.
    """
    name = doc.source_file_name

    concept = doc.concept_sheet
    if concept is None:
        raise BriefMappingError(f"{name}: no 'A. Internal Concept Sheet' section")

    topic_id = doc.topic_id or metadata_of(concept).get("topic id")
    if not topic_id:
        raise BriefMappingError(f"{name}: no topic ID found")

    sequence_no = doc.topic_number
    if sequence_no is None:
        raise BriefMappingError(f"{name}: could not determine the topic number")

    topic_title = doc.topic_title
    if not topic_title:
        raise BriefMappingError(f"{name}: no topic title found")

    values: dict[str, object] = {}

    for field, heading in PROSE_FIELDS.items():
        text = prose_of(concept.subsection(heading))
        if not text:
            raise BriefMappingError(f"{name}: '{heading}' is missing or empty")
        values[field] = text

    for field, heading in SCOPE_FIELDS.items():
        entries = items_of(concept.subsection(heading))
        if not entries:
            raise BriefMappingError(f"{name}: '{heading}' is missing or empty")
        values[field] = entries

    handoff = doc.designer_handoff

    try:
        return NormalizedTopicBrief(
            topic_id=topic_id,
            topic_code=f"T{sequence_no:02d}",
            topic_title=topic_title,
            ks_stage=_ks_stage(doc),
            sequence_no=sequence_no,
            golden_rules=items_of(_find_subsection(handoff, GOLDEN_RULES_HEADING))
            if handoff is not None
            else [],
            storyboard_notes=storyboard_notes_of(handoff),
            source_file_name=name,
            **values,
        )
    except BriefMappingError:
        raise
    except Exception as exc:
        # Pydantic validation failure. Name the document, or the error alone
        # gives no clue which of the six is at fault.
        raise BriefMappingError(f"{name}: {exc}") from exc


def map_all(docs: Optional[list[ParsedTopicDocument]] = None) -> list[NormalizedTopicBrief]:
    """Parse and map every topic document."""
    if docs is None:
        docs = parse_all_topic_documents()
    return [to_normalized_brief(d) for d in docs]


if __name__ == "__main__":
    for brief in map_all():
        print(f"\n{brief.topic_code}  {brief.topic_id}  {brief.topic_title}")
        print(f"  ks_stage       : {brief.ks_stage.value}   seq={brief.sequence_no}")
        print(f"  learning_goal  : {brief.learning_goal[:96]}")
        print(f"  core_message   : {brief.core_message[:96]}")
        print(f"  included       : {len(brief.included_scope)} items")
        print(f"  excluded       : {len(brief.excluded_scope)} items")
        print(f"  misconceptions : {len(brief.misconceptions_to_prevent)} items")
        print(f"  golden_rules   : {len(brief.golden_rules)} items")
        print(f"  storyboard     : {len(brief.storyboard_notes)} chars")
